version: '3.8'

services:
  gpt-nexus:
    build: ./gpt-nexus
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6390
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always

  redis:
    image: "redis:7-alpine"
    ports:
      - "6390:6390"  # changed both sides: external:internal
    command: ["redis-server", "--port", "6390"]
    volumes:
      - redis_data:/data
    restart: always

  postgres:
    image: "postgres:17-alpine"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always

volumes:
  redis_data:
  postgres_data:
