# docker-compose.yml
version: '3.8'

services:
  gpt-nexus:
    build: ./gpt-nexus # Build from the Dockerfile in the gpt-nexus directory
    ports:
      - "8000:8000" # Expose Nexus on port 8000 on the host
    depends_on:
      - redis
      - postgres
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always

  redis:
    image: "redis:7-alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  postgres:
    image: "postgres:17-alpine"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always

  # Future agent services would be added here:
  # gpt-agent_comms:
  #   build: ./gpt-agent_comms
  #   depends_on:
  #     - redis
  #   restart: always

volumes:
  redis_data:
  postgres_data:
